# Enable injecting custom screen resolutions into the game's settings menu (D3D9 only) (Default: false)
EnabledEnumeratedResolutions=true

# Comma-separated list of custom resolutions to be injected (D3D9 only)
ExtraEnumeratedResolutions=2560x1440, 3840x2160

# Enable verbose debug logging to gameplug.log (Default: false)
Debug=false

# Enable Texture Replacement (D3D9 only) (Default: false)
EnableTextureReplacement=false

# Enable the Texture Dumper module (D3D9 only) (Default: false)
EnableDumper=false

# Auto dump bound textures to disk (requires EnableDumper=true) (D3D9 only) (Default: false)
AutoDumpTextures=false

# Enable Vulkan upscaler layer integration (bypasses D3D9 OnRenderFrame and uses vklayer) (Default: false)
VKUpscaler=true
