name: Test Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-build:
    name: Test Build ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config Release
