name: Test Build

on:
  push:
    branches: [ main, dev, upscaler ]
  pull_request:
    branches: [ main, dev, upscaler ]

jobs:
  test-build:
    name: Test Build ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Configure CMake
        run: cmake -B build -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config Release
